name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17.6.0'

    - name: MongoDB Action
      uses: SusanDoggie/mongodb-action@0.0.1

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run lint

    - name: Run Unit Tests
      run: npm test

    - name: Check Code Coverage
      run: npm run test:coverage


    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: application-build
        path: build/
